live_config_reload = true

import = [
  "~/.config/alacritty/defaults.toml",
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
]

[env]
TERM_PROGRAM = 'Alacritty'

[window]
padding = { x = 0, y = 0 }
position = { x = 0, y = 0 }
dimensions = { columns = 134, lines = 100 }
dynamic_padding = true
decorations = "None"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Insert", mods = "Shift", action = "Paste" },
]
