[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true

[general]
import = [
  "~/.config/alacritty/themes/_default.toml",
  "~/.config/alacritty/themes/_current.toml",
]
