#!/usr/bin/env bash

# Customisation of standard behaviour
alias tree='tree -FC'
alias rspec='rspec --color --tty --format documentation'
alias tmux='tmux -u' # force utf-8
alias grep='grep --color=always'
alias less='less -Ri'

ls_opt='--color=auto --group-directories-first --file-type'
alias ls="ls $ls_opt"

if [[ $SYSTEM_TYPE == 'Darwin' ]]; then
	# use GNU ls if it's available
	if (which gls > /dev/null); then
		alias ls="gls $ls_opt"
	else
		alias ls='ls -CFG'
	fi
fi

if [[ $SYSTEM_TYPE == 'Darwin' ]]; then
	if (which gstat > /dev/null); then
		alias stat="gstat"
	fi
fi

alias l='ls -lGgh' # list, omit group, omit owner, human readable sizes
alias ll='ls -la' # list, show all files
alias la='ls -A' # no list, show almost all

# Key-saving shortcuts
alias vi='vim'
alias bx='bundle exec'
alias duh='du -csh'
alias sr='screen -r'
alias t='tmux'
alias ta='t a'

# Kind of new things
alias ff='find . -type f 2>/dev/null| ack -i '
alias heredoc="read -rd '' HEREDOC << 'EOF'"
alias cdr='cd $(git rev-parse --show-cdup)'
