alias vi='vim'
alias sr='screen -r'
alias t='tmux'
alias ta='tmux a'
alias ff='find . | ack '
alias tree='tree -FC'
alias ls='ls -G --color=auto'
alias l='ls -lh'
alias ll='ls -alF'
alias la='ls -A'
alias rspec='rspec --color --tty'
alias bx='bundle exec'
alias z='zeus '
alias r='rails'
alias duh='du -csh'

if [[ $SYSTEM_TYPE == 'Darwin' ]]; then
	alias ls='ls -CFG'
	alias ll='ls -alFG'
	alias la='ls -AG'
	alias l='ls -lh'
fi
