#!/usr/bin/env bash

set -e

wip() {
  git add -A
  git commit --no-verify -m 'wip'
}

unwip() {
  if [ "`git log --format=%B -n 1 HEAD`" = "wip" ]; then
    git reset --soft HEAD~1;
    git reset HEAD;
  fi;
}

uncommit() {
  id=$(git rev-parse --short HEAD)
  title=$(git log --format="%s" -1)
  git reset --soft HEAD~ && echo "Reset commit ${title} (was ${id})."
}

diff_branch() {
  if [[ $1 == *"--"* ]]; then
    branch=$(git rev-parse --abbrev-ref HEAD)
    options=$*
  else
    branch=$1
    options=${@:2}
  fi
  git diff $options $(git merge-base --fork-point origin/$DEFAULT_BRANCH $branch)..$branch
}

log_patch() {
  options=$*
  git --no-pager log --color --patch $options --decorate | less --pattern '^commit'
}

log_patch_reverse_branch() {
  options=$*
  start=$(git merge-base --fork-point origin/$DEFAULT_BRANCH)
  git --no-pager log $start..HEAD --patch --reverse --color $options | less --pattern '^commit'
}

merge_branch_origin_to_master() {
  branch=$(git rev-parse --abbrev-ref HEAD)
  git checkout master
  git merge --no-ff origin/$branch
}

selecta_branch() {
  git branch -a |
    cut -c 3- |
    sed 's:remotes/origin/::' |
    grep -v HEAD |
    sort -u |
    selecta |
    xargs git checkout
}

selecta_recent_branch() {
bash << EOS
  cat <(git reflog -n 100 | grep -E 'checkout:|Branch: renamed' | grep -Eo "\S+$") \
      <(git branch | cut -c 3-) \
      | sed 's:refs/heads/::' \
      | awk '!x[\$0]++' \
      | grep -v $(git rev-parse --abbrev-ref HEAD) \
      | selecta \
      | xargs git checkout
EOS
}

tail_origin_log() {
  log_options=$1
  branch='origin/master'
  interval=360

  while true; do
    clear

    git --no-pager log --color --graph --decorate $log_options $branch -20 \
      | head -n $(expr $(tput lines) - 1)

    sleep $interval

    git fetch
  done
}

pretty_log() {
  git log --graph --pretty=format:"%C(yellow)%h%C(green) %ar%C(blue) %an%C(red)%d%C(reset) %s"
}

pretty_shortdate_log() {
  git --no-pager log --graph --color --pretty=format:"%C(yellow)%h %C(green)|%ar|%C(red)%d%C(reset) %s" \
    | sed -E "s/\|([0-9]+) ([a-z]).*\|/\1\2/" \
    | less
}

new() {
  [ -z $1 ] && >&2 echo "fatal: new directory path required" && exit 1

  mkdir -p "$1"
  git_dir="./${1}/.git"
  git init "$1" \
    && git --git-dir=$git_dir commit --allow-empty -m "Initial commit" \
    && git --git-dir=$git_dir tag root

  [ $TMUX ] && tmux send-keys "cd ${1}" C-m
}

blame_files() {
  arg_files="$*"
  stdin_files=$(cat <&0)  # stdin is file descriptor zero
  for file in $(echo $arg_files $stdin_files); do
    blame_file $file
  done
}

blame_file() {
  file=$1
  git --no-pager log --color=always --date=short --format="%ad•${file}•%C(blue)%an%C(reset)•%C(yellow)%h%C(reset)  %s" -1 $file
}

jcoglan_graph() {
  options="$*"
  git log $options --graph --format="%C(yellow)%h%C(green)%d %C(blue)(%an, %ar) %C(reset)%n%w(72)%s%n"
}

rebase_upstream() {
  options="$*"
  upstream=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})
  git rebase $options $upstream
}

upstream() {
  git rev-parse --abbrev-ref --symbolic-full-name @{u}
}
