unbind C-b

bind -n 'C-\' resize-pane -Z
bind -n C-h run 'tmux-vim-select-pane -L'
bind -n C-j run 'tmux-vim-select-pane -D'
bind -n C-k run 'tmux-vim-select-pane -U'
bind -n C-l run 'tmux-vim-select-pane -R'
bind -n M-l send "C-l"
bind -n M-r source ~/.tmux.conf\; display "Reloaded"
bind -r % splitw -h -c "#{pane_current_path}"
bind -r '"' splitw -c "#{pane_current_path}"
bind -r C-h selectw -t :-
bind -r C-l selectw -t :+
bind -r C-o rotatew
bind -r I run 'tmux-irb #{pane_current_path}'
bind -r M-1 selectl even-horizontal
bind -r M-2 selectl even-vertical
bind -r M-3 selectl main-horizontal
bind -r M-4 selectl main-vertical
bind -r M-5 selectl tiled
bind -r M-6 selectl main-horizontal-mirrored
bind -r M-7 selectl main-vertical-mirrored
bind -r M-l send "C-l"
bind -r M-o rotatew -D
bind -r N run 'tmux-node #{pane_current_path}'
bind -r P run 'tmux-psql #{pane_current_path}'
bind -r T run 'tmux-todo #{pane_current_path}'
bind -r t popup -E 'tmux-fzf-window'
bind C-Space send-prefix
bind Enter run-shell "tmux switch-client -l" \; run-shell "tmux kill-session -t #{session_name}"
bind S popup -E 'tmux-project-session'
bind Z popup -E 'tmux-fzf-command-history'
bind [ run-shell "tmux-copy-mode-with-line-numbers"
bind b run-shell "tmux-move-to-new-session"
bind c neww -c "#{pane_current_path}"
