set -ag command-alias 'diff-keys=split-window -Z tmux-diff-keys'
set -ag command-alias 'diff-options=split-window -Z tmux-diff-options'
set -g base-index 1
set -g default-command "$SHELL"
set -g display-time 2000
set -g focus-events on
set -g history-file ~/.tmux_history
set -g history-limit 5000
set -g mouse on
set -g pane-active-border-style "fg=brightblack"
set -g pane-border-lines heavy
set -g pane-border-style "fg=brightblack"
set -g prefix C-Space
set -g renumber-windows on
set -g status off
set -g status-interval 1
set -g status-keys emacs
set -g status-left-length 30
set -g status-right "#{?#{==:#{@git-info},on},#(POWERLINE=false tmux-git-info '#{pane_current_path}'),}#[fg=green,bg=default] #[fg=darkgreen,bg=green] %a %-d %b %R #[default]"
set -g status-right-length 100
set -g status-style "fg=default,bg=default"
set -g update-environment "DISPLAY KRB5CCNAME SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY TERM_APP TERM_PROFILE HYPRLAND_INSTANCE_SIGNATURE"
set -sg escape-time 1
setw -g menu-selected-style "fg=default"
setw -g mode-keys vi
setw -g monitor-activity on
setw -g pane-base-index 1
setw -g popup-border-lines rounded
setw -g popup-border-style "fg=brightblack"
setw -g status-left "#[fg=green,bg=terminal]#[fg=darkgreen,bg=green] #{session_name} #[fg=green,bg=default] "
setw -g status-left-style "bright"
setw -g window-status-activity-style "fg=default bg=default"
setw -g window-status-current-format "#[fg=white,bg=brightblack] #I.#{pane_index}:#W#{?window_flags,#{window_flags}, } #[default]"
setw -g window-status-current-style "bright"
setw -g window-status-format "#I.#{pane_index}:#W#{?window_flags,#{window_flags}, }"
setw -g window-status-style "dim italics"
