set -g @min-pane-height 40
set -g @git-info on
set -g @tmux-git-info-min-width 100
set -g @status-right-clock "#[fg=green,bg=default] #[fg=darkgreen,bg=green] %a %-d %b %R#[fg=green,bg=default]#[default]"
